### ISSUE TITLE
[R&D task] Deploy the server and make a CI/CD pipeline

### ISSUE THREAD

**Issue by Polarts** [haifa-dev/server#1]
The server should be ready to deploy by now, right?
It's time to make it happen and let it run on some cloud.

The important part is to have a CI/CD for it, so that master is always deployed as soon as it's ready.

Steps: 
- Find a suitable host that's always free and offers GitHub integration.
- Comment here a link and explain why it's good (pros/cons etc...)
- I'll create an account.
- We'll establish a pipeline.

The sooner the better, if possible then this weekend.

**Comment by gioragutt** [comment]
How about creating a `Github Actions` pipeline that deploys the site as to github-pages?

**Comment by Polarts** [comment]
Is it relevant for back-end?

**Comment by gioragutt** [comment]
Yeah I didn't think about that fact that it's for the backend and not the front
